### PR TITLE
Add tags, search by tags, and deprecate some functions [CFG-72]

### PR DESCRIPTION
**Pull request by haroldcb**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17)

### CODE REVIEW

**Review by conord33 — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb and @Paturages)

___
*[SDKTest/SdkTest.cs, line 306 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/17#-MW3X7CKCmdGPHGX2vre:-MW3X7CL7Uq8kZvh6BXB:b302pnr) ([raw file](https://github.com/stratumn/sdk-csharp/blob/d8a7a6a2a4aa05d12a3ab0dfdd8fd7fb4bca33eb/SDKTest/SdkTest.cs#L306)):*
> ```Smalltalk
> 
>         [Fact]
>         [Obsolete("RejectTransferTest is deprecated")]
> ```

:thumbsup: good idea

**Review by Paturages — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17#-:-MW9-Ei73YRQN_7KGAcJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb)

**Review by conord33 — COMMENTED** [review]
@paturages are you familiar with the release process on this sdk?

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17#-:-MWNv-Y8EcCrPS2fI7rm:b-rnxzny)* status: all files reviewed, 1 unresolved discussion

**Review by Paturages — COMMENTED** [review]
@conord33 some distant memories from [this](https://github.com/stratumn/sdk-csharp#publishing-to-nuget) and [this](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli), I think to upgrade a package, you should bump the version number manually in the .csproj, build and publish the resulting new version. To publish to nuget, you need to have an account there that's added to the stratumn org, which is owned by... uuuuuh fuck


> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17#-:-MWOA9zmBANNx7JQBk6v:b66fghs)* status: all files reviewed, 1 unresolved discussion

**Review by conord33 — COMMENTED** [review]
hahahaha ill see if mourad is nice enough to add another amdin...

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/17#-:-MWOOyLZ1Evh3kieB38L:b-q37yaj)* status: all files reviewed, 1 unresolved discussion

**Comment by bejito** [comment]
You can use stratumn-dev for that. The credentials should be on 1password. And feel free to remove me from this !! I'm sure I'll sleep much better once that's done

**Pull request merged**
