### PR TITLE
Update tests and fix file import

### PR DESCRIPTION
**Pull request by haroldcb**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26)

### CODE REVIEW

**Review by Paturages — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-:-Mac-xD68NLHiw2dAjTm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @conord33 and @haroldcb)

___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-MabzwT363SvO2JuvhBU:b-iczdl3) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
> ```Smalltalk
>     {
>         // Env dependant
>         // FIXME : set these in semaphore ?
> ```

same as java sdk: ideally we'd put these in environment variables

**Review by conord33 — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26)* status: all files reviewed, 1 unresolved discussion (waiting on @Paturages)

___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-MbLIzybBQpt6RrvEmZB:b-csf0kj) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

same as java sdk: ideally we'd put these in environment variables
</blockquote></details>

yeah lets add these in the env files in sem they can all share the same one. i think the main concern is the private keys... we dont really want those to be public... the annoying thing is making them accessible for local dev though...

**Comment by haroldcb** [comment]
___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-MbLKMnj0kSiQ3x-Qzto:b32j1j3) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

yeah lets add these in the env files in sem they can all share the same one. i think the main concern is the private keys... we dont really want those to be public... the annoying thing is making them accessible for local dev though...
</blockquote></details>

The private key can be found here : https://github.com/stratumn/trace-generator/pull/118/files, in the examples/sdksTest/accounts/keys.ts, if we add something in the readme to explain where to find them is it ok ?

**Review by conord33 — APPROVED** [review]
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb and @Paturages)

___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-MbLKvvd6tfknKjJ81oV:bcvqw14) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

The private key can be found here : https://github.com/stratumn/trace-generator/pull/118/files, in the examples/sdksTest/accounts/keys.ts, if we add something in the readme to explain where to find them is it ok ?
</blockquote></details>

yeah that should work since it is a private repo

**Review by conord33 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb and @Paturages)

___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-MbLL1FOCtcOA0oST11C:b-smfbxx) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

yeah that should work since it is a private repo
</blockquote></details>

so we can add a staging env file on sem that can contain these values + the signing keys. i can show you how to add that to semaphore once you have the file you need to add. probably good to have a `.env.dist` with example values too. all the staging values except the private keys should be okay to keep in that `.env.dist` file.

**Comment by haroldcb** [comment]
___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-Mc9mwkN30HBEyYHM1S8:bi35nk4) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

so we can add a staging env file on sem that can contain these values + the signing keys. i can show you how to add that to semaphore once you have the file you need to add. probably good to have a `.env.dist` with example values too. all the staging values except the private keys should be okay to keep in that `.env.dist` file.
</blockquote></details>

@conord33 : do you have time this week to show me please ?

**Review by conord33 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-csharp/26)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb and @Paturages)

___
*[SdkTest/ConfigTest.cs, line 6 at r1](https://reviewable.io/reviews/stratumn/sdk-csharp/26#-MabzwT363SvO2JuvhBT:-McAHJQaCOVsVC3v3nWw:b-ydufbb) ([raw file](https://github.com/stratumn/sdk-csharp/blob/1fc8ec487e9f542d3c7fd991f7bc588a7cb4d7f1/SdkTest/ConfigTest.cs#L6)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

@conord33 : do you have time this week to show me please ?
</blockquote></details>

just setup a meeting for tomorrow morning :)

**Pull request merged**
